### PR TITLE
save the registration after weve updated it

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Fixes imported payments always being "pending payment" even when fully paid.
This was a bug because we switched to updating the payment status later during the request, and now need to resave the registration.

## How has this been tested

* [x] Create an event with a $10 ticket. Import attendees to it from the sample CSV. One should be approved, the other pending payment.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by mnelson4** [comment]
@joshfeck can you test or assign to someone else?

**Comment by joshfeck** [comment]
I'm glad you caught this!

**Comment by mnelson4** [comment]
TBH I've been surprised at how brittle this has all been. I thought "nah, we don't need unit tests for this, it's so straightforward" but I'm rethinking that. Especially consider how its relying on some EE core code that could change...

**Comment by mnelson4** [comment]
Also, Lorenzo independently discovered this on https://github.com/eventespresso/eea-importer/pull/65#issuecomment-506436785

**Pull request merged**
