### PR TITLE
Task/generic name

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Makes the admin menu item's name more generic, which we'll probably want for when there are multiple importers. Although doesn't rename all the classes. I'm looking for feedback on what others would like here.

## How has this been tested

* [ ] The admin menu item should now just be "Importer", 
* [ ] You should still be able to get to the attendee importer

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by mnelson4** [comment]
Yeah thanks. @joshfeck do you approve? Here's a preview:
screenshot-laragonee test-2019 05 08-10-51-25

If so, maybe we should also rename the plugin name to also just be "Importer"? (Other importers could either be contained in this add-on, or could be add-ons-for-the-add-on, although I remember we didn't like that type of chained dependency)
Also, if you approve I'd be inclined to rename a few of the classes and folders etc too.

**Comment by joshfeck** [comment]
Yeah I think the direction you're taking this is fine since it probably simplifies things having one importer add-on for everything, or at least for most things.

**Comment by joshfeck** [comment]
I agree that the "Import Contacts from CSV File" text would be better if replaced with "Attendee Importer" because that text shows up on every step. 

Also, if we are going to be adding more importers, maybe the tab navigation would be useful? If so, then the "Import" label on the tab could say "Import Attendees" instead.

**Comment by mnelson4** [comment]
touched basically every file in order to rename from "Attendee importer" to just "Importer" (except for the manager and associated code which actually does just deal with importing attendees).

**Comment by joshfeck** [comment]
This can be merged.

**Comment by mnelson4** [comment]
right on

**Pull request merged**
