### PR TITLE
Task/remove unused files

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Removes several unused files. Funtionality shouldn't be affected.

## How has this been tested

* [ ] Verify you can still run an import fine like before

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by mnelson4** [comment]
I think we may want to test this, just to double-check I didn't accidentally delete anything important (at one point, while working on this, I got a little greedy and did but caught myself before committing it.)

**Comment by joshfeck** [comment]
We should probably either remove or update the ee3-attendee-importer-sample files because EE4's importer doesn't support the Payment Status and Price Option fields.

**Comment by joshfeck** [comment]
I tested the importer and it doesn't look like anything got removed that shouldn't have.

I went ahead and removed the EE3 import file examples, and updated the one example file to include the payment amount fields and renamed it. 

If the last two changes look good then it's ready for merging.

**Comment by mnelson4** [comment]
Thanks @joshfeck. Ya it's probably best to just have one sample CSV (it was kinda convenient having those variations for testing, but you're right, definetely not in the release.)

**Pull request merged**
