### PR TITLE
make sure the registration we get from the command matches whats in t…

### PR DESCRIPTION
**Pull request by mnelson4**
…he model entity map

## Problem this Pull Request solves

On EventSmart (and probably while using Infusionsoft) if you import an attendee with a payment, the registration gets saved without an ATT_ID. That's because if an add-on hooks into `AHEE__EEM_Base__insert__end`, and then fetches the model object from the ID, the model's entity map will end up with a different model object than the code that called `save` on the model object (so there is one in the entity map, and the other isn't). Later on when we set the `ATT_ID` on the registration that's not in the entity map, and go to save it, it works BUT the other registration in the entity map can get saved, and overwrite it.

(Note: Other code should probably hook in AFTER the model object has been saved to the entity map, rather than before it; we could make another ticket to do that.)

This resolves the problem by, immediately after saving the registration, replacing it with what's in the entity map (if they're the same, no problem too). This way we avoid having two model object floating around representing the same database row.

see https://github.com/eventespresso/eventsmart.com-website/issues/470#issuecomment-505947919

## How has this been tested

* [ ] With no other add-ons active, do an import using the payment row. It should work fine.
* [ ] Repeat the above but with the Infusionsoft add-on active. The result should be the same.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by mnelson4** [comment]
@lorenzocaum do you mind taking a stab at testing this? If not please pass to Josh for triage.

**Comment by lorenzocaum** [comment]
Hey Mike, I got a copy of master and the entity-map branch and the payments are coming through with or without Infusionsoft. 

However, I noticed that the registration status is still set to pending payment.

Image 2019-06-27 at 1 18 30 PM

I checked the transactions and they are complete:

Image 2019-06-27 at 1 19 46 PM

Here is what a specific transaction looks like:

Image 2019-06-27 at 1 21 31 PM

**Comment by mnelson4** [comment]
Hi @lorenzocaum I actually created [a separate issue for that](https://github.com/eventespresso/eea-importer/issues/66) (you should see that same thing with master branch previously), and it should actually be fixed now on master and this branch. 
Re-test please?

**Comment by lorenzocaum** [comment]
Hi Mike, thanks for the heads up. I retested with Infusionsoft off and that worked. I then tested with Infusionsoft on and the registrations imported with the payment and are approved.

Could you merge this in?

Then could you please cherry pick the additional fix here (https://github.com/eventespresso/eea-importer/pull/67) into this pull request (https://github.com/eventespresso/eventsmart.com-website/pull/521) and then merge to Make Events Not War staging?

I can then run through testing so we can relaunch the Attendee Importer service on Event Smart.

**Comment by mnelson4** [comment]
Kk I updated the EventSmart branch with #67 's changes (we should probably continue this discussion on that EventSmart branch)

**Pull request merged**
