### PR TITLE
Don't autofill event or ticket

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Don't autofill the event or ticket steps with the selection from a previous event. Often users should change those for subsequent imports, so if we autofill them users are likely to import to the wrong event or ticket. See https://github.com/eventespresso/eea-importer/issues/39

## How has this been tested

* [x] Create two events (event A and event B), each with two tickets. Import attendees into event A. Begin another import, but select event B. When you come to the ticket selection step, there should be NO ticket pre-selected (because the ticket it would have pre-selected would ahve been for event A, but we already indicated this import should be for event B). 
* [x] Continuing from the last test, press back in your browser. Select event A again. During the event selection step, the event should NOT be auto-selected; ticket selection step, the ticket should NOT be auto-selected. All other steps should be unaffected (most notably, the mapping step should still remember your mapping selections from previous imports.)

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by mnelson4** [comment]
Passing to @tn3rb for review.

**Comment by joshfeck** [comment]
Hey Mike I'm curious why there's a default selection of a previous ticket. Wouldn't that make for a gotcha in most use cases?

For example, let's say I have an event with two tickets, and I have two sets of registration lists, for each respective ticket, to upload. I upload the first, then when I go to upload the second list I forget to select the second ticket (because the first ticket was selected by default). Now I've got two imports and both got imported to the first ticket.

Is there a reason to default to a previously selected ticket?

**Comment by mnelson4** [comment]
Right now, it saves all the configuration from the last import (except the actual file, although we could), so I both preselecting the ticket was both the default, and I thought people may be importing registrations from multiple files for the same ticket (especially when we avoid creating duplicates, see https://github.com/eventespresso/eea-importer/issues/26). On the Black tie and boots website, they re-uploaded the same CSV multiple times because they added a few more registrations after the initial upload, and in those cases preselecting the ticket seems helpful.
But if you'd rather not have it it's easy to remove.

**Comment by mnelson4** [comment]
Oh also: we remember the last-selected ticket because it's possible the did all the steps except the last one, (eg because they forgot to backup their database), then it's nice to have their previous choice pre-selected.

If the above makes you think it's better to continue remembering the user's last-selected ticket, feel free to confirm the expected behaviour. But if you'd rather remove it altogether, just pass on back.

**Comment by joshfeck** [comment]
The problem with the current behavior is if you do nothing on the selection step, you can end up with registrations for the wrong ticket. Since these can be very difficult to delete, when an option is presented like "select a ticket", then the user must make the selection. Instead of just confirming a selection. It's too easy to make a mistake the way it is now.

**Comment by mnelson4** [comment]
Hmmm so would you also like to avoid remembering what event the user selected last time too? But would you like to continue remembering the column mapping?

**Comment by joshfeck** [comment]
Event no, column mapping yes because that could be helpful to reuse column mappings for every event.

**Comment by mnelson4** [comment]
Kk! So I just won’t autofill the event and ticket selection forms then. Easy peasy!

**Comment by mnelson4** [comment]
Off for review again @tn3rb! I've updated the ticket's name and description to reflect the new expected behaviour.

**Pull request merged**
